spring:
  jpa:
    show-sql: false
    database-platform: com.mindata.blockchain.core.sqlite.config.SQLiteDialect
    generate-ddl: true
sqlite:
  dbName: a.db  #本地sqlite的名字
db:
  levelDB: true    #在部分Windows机器上rocksDB会报错dll找不到，那么就用levelDB来替代
  rocksDB: false
version: 1
name: ${NAME:maida}
appId: ${APP_ID:wolf}
managerUrl: ${MANAGER_URL:http://localhost:8888/}